services:
  client:
    container_name: think_dev_client
    build: ./client
    image: think_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: think_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=thinkpass
      - PGDATABASE=think
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: think_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=think
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=thinkpass
volumes:
  dbdata:
networks: 
  default:
    name: think_api
