services:
  api:
    container_name: think_test_api
    environment: 
      - PGUSER=me
      - PGHOST=db
      - PGPASSWORD=thinkpass
      - PGDATABASE=think_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: think_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=think_test
      - POSTGRES_PASSWORD=thinkpass
volumes:
  test_db:
networks: 
  default:
    name: think_test
